language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- pip install coverage
- pip install coveralls
script: coverage run -m unittest discover -s tests
notifications:
  email: false
before_deploy:
- echo "${SSH_DEPLOY_PUBLIC_KEY}" >> $HOME/.ssh/known_hosts
- eval "$(ssh-agent)"
- ssh-add - <<< base 64 --decode "${SSH_DEPLOY_PRIVATE_KEY}"
deploy:
  provider: pypi
  username: __token__
  password:
    secure: GtIaf9BmJQ2MDJye5/kgfO85ZRuF5ArNmz+MwPBhHpYxxu6uHwzeE20LP9Cjr9y0RGt2jMcC7N4TwBd70fTITZg6LIgji651gSX4ALg4ypSDUdImDbjLTVUVE6ta8bvj8bHm2If2uhppjIRg3VE7F7wKobzei1hK6qP73h14GjHFjLUmKFagbveES09TJClRaqnOL6TFuKi/w3BbymUydBc0ditqc4p4o4BnaDFkk9ymBNQzLvFsR/xVbkFSoP7bEQQ7bGYSrTcYUB4RLChsxVdiOVmxWAg+9R744jI+BowQxwLmxcdIVv3si/W74TkHXbYCHYukz5VuI1qlt+PpY2pDIJ+GpgAMaOrLHrV0iNltNII8Mqw3hmomgUUdMVU8GqvbRbBZD6a8AYlKNj8a9g/b4/ZkOdkKZDW5VOtYwbUlsb7FaDLa0xtKIIA2XoApczNebSBWWXJZaSPk9/Wf98z/9+exXjj0VfqlBENQ18/O0I+hhzw51oa6ATVXSm+OapAx+oIEimPrL6oZslYDsplw5TmMmlo20ehzhDhRPwiF3Q2UIwIHvR02mys55Zu9RwF7FMKL5/RIrI0RZfQn7H57vh6TpmeL2jFYFpQs1wKi2kafGo9Zjv9anv4SLJ3PQSpwCT5PWDGFOFYb04HmhiRusfjU3LT4B96hJBbBdvY=
  on:
    tags: true
  distributions: sdist bdist_wheel
env:
  global:
    - SSH_DEPLOY_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCaKrsdzk2r9nLxqyq19NoIf4lcVZdtvPlrA6D6uG5UDSPIykaFsRtyJkzwqomFxHQlOrYfi8UjcSE9JtgHO/1vNzyLNDnDkJRUprR9mxpfWgJ1GezPH3cykfK1mwkDn+b7c9vmTs6zrHnVCq+U8OrciSOqkELrCNX/o2kF3jqtJkMlJ32yNE/eP4FkRGy835vPQ2VKmdxjqlIerv92pDv9UwLNBd5sLu7jFDMxnvE8cnON9TxqhAdT+UlRe61O2hX77eTVjtlbEsLu1wRxfT3QhMbmldsiyYTFBLpNxuXDHXZvkQXlyyPdAYbfxA5/GamCIrierM6uQGpHpcU85cT build@travis-ci.org"
after_success:
  - coveralls